import { Product, Country, ProspectBuyer, Supplier, Exhibition, Competitor } from "./types";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "IQF Strawberry",
    code: "STRW-01",
    category: "Fruit",
    seasonStart: "December",
    seasonEnd: "April",
    targetTemp: "-18°C",
    description: "Premium hand-picked Egyptian strawberries (Festival/Fortuna varieties), washed, calibrated, individually quick frozen, and sorted under strict quality control. High sweetness index (Brix) and bright red color.",
    hsCode: "0811.10"
  },
  {
    id: "prod-2",
    name: "IQF Mango",
    code: "MNG-02",
    category: "Fruit",
    seasonStart: "July",
    seasonEnd: "November",
    targetTemp: "-18°C",
    description: "Egyptian premium Mango (Zebdia/Yasmina varieties), peeled, diced into 10x10mm cubes or sliced, quick-frozen. No sugar or preservatives added. Rich aroma and vibrant orange-yellow flesh.",
    hsCode: "0811.90"
  },
  {
    id: "prod-3",
    name: "IQF Broccoli",
    code: "BRC-03",
    category: "Vegetable",
    seasonStart: "November",
    seasonEnd: "March",
    targetTemp: "-18°C",
    description: "Fresh broccoli heads cut into florets (20-40mm or 40-60mm), blanched, and individually quick frozen. Perfect dark green retention and crisp texture.",
    hsCode: "0710.80"
  },
  {
    id: "prod-4",
    name: "IQF Okra",
    code: "OKR-04",
    category: "Vegetable",
    seasonStart: "June",
    seasonEnd: "October",
    targetTemp: "-18°C",
    description: "Egyptian Okra (Zero, Excellent, Fine, and One sizes), cap-trimmed, blanched, and frozen. Excellent slime-reduction processing, beautiful deep green color.",
    hsCode: "0710.80"
  },
  {
    id: "prod-5",
    name: "IQF Molokhia",
    code: "MLK-05",
    category: "Vegetable",
    seasonStart: "May",
    seasonEnd: "September",
    targetTemp: "-18°C",
    description: "Minced Egyptian jew's mallow leaves, mixed with water (or plain), packed in retail or bulk pouches and frozen. High viscosity and original traditional green taste.",
    hsCode: "0710.80"
  },
  {
    id: "prod-6",
    name: "IQF Green Beans",
    code: "GNB-06",
    category: "Vegetable",
    seasonStart: "October",
    seasonEnd: "April",
    targetTemp: "-18°C",
    description: "Fine green beans, cut (2-4cm) or whole, stringless, blanched, and quick-frozen. Uniform color, tender and crunchy biting profile.",
    hsCode: "0710.22"
  },
  {
    id: "prod-7",
    name: "IQF Mixed Vegetables",
    code: "MXV-07",
    category: "Mixed",
    seasonStart: "Year-round",
    seasonEnd: "Year-round",
    targetTemp: "-18°C",
    description: "Colorful blend of diced carrots, green peas, sweet corn, and cut green beans in balanced proportions. Blanched and frozen individually.",
    hsCode: "0710.90"
  }
];

export const INITIAL_COUNTRIES: Country[] = [
  {
    id: "c-usa",
    name: "USA",
    code: "US",
    flag: "🇺🇸",
    population: "340M",
    foodImportValue: "$185B",
    vegImportValue: "$2.4B",
    currency: "USD ($)",
    language: "English",
    ports: ["New York", "Los Angeles", "Savannah", "Houston"],
    tariffRate: "2.1% (Depends on FTA status)",
    certificates: ["FDA Registration", "FSVP", "BRCGS", "KOSHER", "Organic (USDA)"],
    marketVibe: "Excellent"
  },
  {
    id: "c-canada",
    name: "Canada",
    code: "CA",
    flag: "🇨🇦",
    population: "39M",
    foodImportValue: "$48B",
    vegImportValue: "$850M",
    currency: "CAD ($)",
    language: "English & French",
    ports: ["Vancouver", "Montreal", "Halifax"],
    tariffRate: "0% - 3.5%",
    certificates: ["CFIA License", "SFCR Compliance", "BRCGS", "ISO 22000"],
    marketVibe: "Good"
  },
  {
    id: "c-germany",
    name: "Germany",
    code: "DE",
    flag: "🇩🇪",
    population: "84M",
    foodImportValue: "$98B",
    vegImportValue: "$1.2B",
    currency: "EUR (€)",
    language: "German",
    ports: ["Hamburg", "Bremerhaven"],
    tariffRate: "0% (EU Common Customs)",
    certificates: ["IFS Food", "BRCGS", "ISO 22000", "Organic (EU)", "BSCI"],
    marketVibe: "Excellent"
  },
  {
    id: "c-france",
    name: "France",
    code: "FR",
    flag: "🇫🇷",
    population: "68M",
    foodImportValue: "$72B",
    vegImportValue: "$950M",
    currency: "EUR (€)",
    language: "French",
    ports: ["Le Havre", "Marseille", "Fos-sur-Mer"],
    tariffRate: "0%",
    certificates: ["IFS Food", "BRCGS", "ISO 22000", "Ecocert Organic"],
    marketVibe: "Excellent"
  },
  {
    id: "c-italy",
    name: "Italy",
    code: "IT",
    flag: "🇮🇹",
    population: "59M",
    foodImportValue: "$55B",
    vegImportValue: "$620M",
    currency: "EUR (€)",
    language: "Italian",
    ports: ["Genoa", "Trieste", "La Spezia"],
    tariffRate: "0%",
    certificates: ["IFS Food", "BRCGS", "ISO 22000", "Halal Certification"],
    marketVibe: "Good"
  },
  {
    id: "c-spain",
    name: "Spain",
    code: "ES",
    flag: "🇪🇸",
    population: "47M",
    foodImportValue: "$45B",
    vegImportValue: "$580M",
    currency: "EUR (€)",
    language: "Spanish",
    ports: ["Valencia", "Algeciras", "Barcelona"],
    tariffRate: "0%",
    certificates: ["IFS Food", "BRCGS", "GLOBALG.A.P.", "ISO 22000"],
    marketVibe: "Good"
  },
  {
    id: "c-poland",
    name: "Poland",
    code: "PL",
    flag: "🇵🇱",
    population: "38M",
    foodImportValue: "$32B",
    vegImportValue: "$480M",
    currency: "PLN (zł)",
    language: "Polish",
    ports: ["Gdansk", "Gdynia"],
    tariffRate: "0%",
    certificates: ["IFS Food", "ISO 22000", "BRCGS"],
    marketVibe: "Excellent"
  },
  {
    id: "c-uk",
    name: "UK",
    code: "GB",
    flag: "🇬🇧",
    population: "67M",
    foodImportValue: "$68B",
    vegImportValue: "$1.1B",
    currency: "GBP (£)",
    language: "English",
    ports: ["Felixstowe", "Southampton", "London Gateway"],
    tariffRate: "2.0% - 4.5%",
    certificates: ["BRCGS (Highly Required)", "IFS Food", "ISO 22000", "Red Tractor (Optional)"],
    marketVibe: "Excellent"
  },
  {
    id: "c-saudi",
    name: "Saudi Arabia",
    code: "SA",
    flag: "🇸🇦",
    population: "36M",
    foodImportValue: "$22B",
    vegImportValue: "$410M",
    currency: "SAR (ر.س)",
    language: "Arabic",
    ports: ["Jeddah Islamic Port", "King Abdulaziz Port (Dammam)"],
    tariffRate: "5.0% - 15.0%",
    certificates: ["SFDA Approval", "Halal Certified (Required)", "SABER Registration", "ISO 22000"],
    marketVibe: "Excellent"
  },
  {
    id: "c-uae",
    name: "UAE",
    code: "AE",
    flag: "🇦🇪",
    population: "10M",
    foodImportValue: "$18B",
    vegImportValue: "$350M",
    currency: "AED (د.إ)",
    language: "Arabic & English",
    ports: ["Jebel Ali (Dubai)", "Khalifa Port (Abu Dhabi)"],
    tariffRate: "5% (Except direct GCC imports)",
    certificates: ["MOIAT Registration", "Halal Certified", "SABER / Food Import Permit", "HACCP"],
    marketVibe: "Excellent"
  },
  {
    id: "c-japan",
    name: "Japan",
    code: "JP",
    flag: "🇯🇵",
    population: "124M",
    foodImportValue: "$75B",
    vegImportValue: "$1.5B",
    currency: "JPY (¥)",
    language: "Japanese",
    ports: ["Tokyo", "Yokohama", "Kobe", "Osaka"],
    tariffRate: "3.0% - 8.5%",
    certificates: ["MHLW Food Sanitation Act", "JAS Certification", "HACCP", "ISO 22000"],
    marketVibe: "Competitive"
  },
  {
    id: "c-korea",
    name: "South Korea",
    code: "KR",
    flag: "🇰🇷",
    population: "51M",
    foodImportValue: "$42B",
    vegImportValue: "$820M",
    currency: "KRW (₩)",
    language: "Korean",
    ports: ["Busan", "Incheon"],
    tariffRate: "5.0% - 20.0%",
    certificates: ["MFDS Clearance", "HACCP Certification", "ISO 22000"],
    marketVibe: "Good"
  },
  {
    id: "c-brazil",
    name: "Brazil",
    code: "BR",
    flag: "🇧🇷",
    population: "215M",
    foodImportValue: "$14B",
    vegImportValue: "$180M",
    currency: "BRL (R$)",
    language: "Portuguese",
    ports: ["Santos", "Paranagua"],
    tariffRate: "10.0% - 14.0% (Mercosur Tariff)",
    certificates: ["MAPA Registration", "ANVISA Clearance", "ISO 22000"],
    marketVibe: "Competitive"
  }
];

export const INITIAL_BUYERS: ProspectBuyer[] = [
  {
    id: "buyer-1",
    name: "Edeka Fruchtkontor & Frozen GmbH",
    country: "Germany",
    city: "Hamburg",
    website: "https://www.edeka.de",
    email: "fruchtkontor@edeka.de",
    procurementEmail: "fruchtkontor@edeka.de",
    realEmail: "info@edeka.de",
    phone: "+49 40 6378-0",
    realPhone: "+49 40 6378-0",
    headquartersAddress: "New-York-Ring 6, 22297 Hamburg, Germany",
    contactVerified: true,
    linkedIn: "https://linkedin.com/company/edeka-group",
    purchasingManager: "Dr. Marcus Weber",
    procurementRole: "Senior Category Director - Frozen Produce & Direct Imports",
    importerType: "Retail Chain Buy-House",
    companySize: "Large",
    employees: 1500,
    yearsInBusiness: 45,
    importsFromEgypt: true,
    importsFromTurkey: true,
    importsFromChina: false,
    importsFromIndia: false,
    competitiveOpportunity: "High. Seeking secondary source for IQF Strawberry due to weather shortages in Poland. They require IFS certificate.",
    recentTriggers: ["Seeking Direct Egyptian Supplier for IQF Crops", "Replacing Shortages from Polish Supply", "Expanding Private Label Frozen Line"],
    requiredCrops: ["IQF Strawberry", "IQF Broccoli", "IQF Mango"],
    certificationsRequired: ["IFS Food v8", "BRCGS Food Safety Grade AA"],
    annualImportVolume: "60 - 100 FCL Containers / Year",
    sourcingChannel: "Supermarket Retail Line",
    incoterms: "CFR Hamburg / Bremerhaven",
    paymentTerms: "100% Confirmed Irrevocable LC at Sight",
    destinationPort: "Port of Hamburg",
    mrlCompliance: "EU MRL ≤ 0.01 mg/kg + SGS / Eurofins Lab Analysis Certificate",
    intentSignalScore: 98,
    aiScore: 96,
    status: "Negotiation",
    notes: "Sent initial catalog. Received interest in IQF Strawberry & IQF Broccoli. Sending samples next week.",
    lastContactDate: "2026-07-10",
    emailsSentCount: 2
  },
  {
    id: "buyer-2",
    name: "Almarai Co. (Frozen Materials Div)",
    country: "Saudi Arabia",
    city: "Riyadh",
    website: "https://www.almarai.com",
    email: "procurement@almarai.com",
    procurementEmail: "procurement@almarai.com",
    realEmail: "info@almarai.com",
    phone: "+966 11 470 0005",
    realPhone: "+966 11 470 0005",
    headquartersAddress: "Exit 7, Al-Izdihar, Riyadh 11492, Saudi Arabia",
    contactVerified: true,
    linkedIn: "https://linkedin.com/company/almarai-co-",
    purchasingManager: "Eng. Faisal Al-Subaie",
    procurementRole: "Head of Agricultural Raw Materials & IQF Sourcing",
    importerType: "Food Factory",
    companySize: "Large",
    employees: 8500,
    yearsInBusiness: 49,
    importsFromEgypt: true,
    importsFromTurkey: false,
    importsFromChina: false,
    importsFromIndia: true,
    competitiveOpportunity: "Excellent. Heavy requirement for IQF Mango pulp & IQF Strawberry for yoghurt lines. Strong trade relationship with Egypt.",
    recentTriggers: ["Expanding Dairy & Puree Processing Lines", "Direct Import Contract with Egyptian Processors"],
    requiredCrops: ["IQF Mango (Diced 10x10)", "IQF Strawberry", "Fruit Concentrates"],
    certificationsRequired: ["Halal Certified", "ISO 22000", "SFDA Registered"],
    annualImportVolume: "120 - 180 FCL Containers / Year",
    sourcingChannel: "Food Processing / Manufacturing",
    incoterms: "CFR Jeddah Islamic Port / Dammam",
    paymentTerms: "CAD (Cash Against Documents) via National Commercial Bank",
    destinationPort: "Jeddah Islamic Port",
    mrlCompliance: "SFDA Agricultural Inspection & Residue Clearance Seal",
    aiScore: 98,
    intentSignalScore: 99,
    status: "Won",
    notes: "Contract signed for 120 Metric Tons of IQF Mango cubes 10x10mm. Shipping schedule starts August.",
    lastContactDate: "2026-07-14",
    emailsSentCount: 4
  },
  {
    id: "buyer-3",
    name: "Sysco Foods UK Ltd (Fresh & Frozen Desk)",
    country: "UK",
    city: "London",
    website: "https://www.sysco.co.uk",
    email: "procurement@sysco.com",
    procurementEmail: "procurement@sysco.com",
    realEmail: "info@sysco.co.uk",
    phone: "+44 20 8477 5000",
    realPhone: "+44 20 8477 5000",
    headquartersAddress: "Enterprise House, Eureka Business Park, Ashford TN25 4AG, UK",
    contactVerified: true,
    linkedIn: "https://linkedin.com/company/sysco-uk",
    purchasingManager: "Jane Cartwright",
    procurementRole: "Senior Purchasing Manager - Global Frozen Vegetables & HoReCa",
    importerType: "Food Service Distributor",
    companySize: "Large",
    employees: 4500,
    yearsInBusiness: 32,
    importsFromEgypt: false,
    importsFromTurkey: true,
    importsFromChina: true,
    importsFromIndia: false,
    competitiveOpportunity: "Good. Currently sourcing IQF Okra and Green Beans from Turkey. Egyptian green beans offer a 15% cost advantage.",
    recentTriggers: ["Seeking Direct Egyptian Supplier for IQF Crops", "Replacing High-Cost European Suppliers"],
    requiredCrops: ["IQF Green Beans Cut (3cm)", "IQF Okra Zero", "IQF Artichoke Bottoms"],
    certificationsRequired: ["BRCGS Food Safety Grade AA", "Red Tractor Assurance Alignment"],
    annualImportVolume: "80 - 140 FCL Containers / Year",
    sourcingChannel: "Foodservice Wholesaler",
    incoterms: "CFR Felixstowe / London Gateway",
    paymentTerms: "30% Advance + 70% against BL & Certificate of Origin",
    destinationPort: "Port of Felixstowe",
    mrlCompliance: "Strict UK FSA / MRL Multi-Residue Lab Screen",
    aiScore: 92,
    intentSignalScore: 94,
    status: "Sample Sent",
    notes: "Samples of IQF Green Beans cut (3cm) delivered to London hub on July 05. Awaiting laboratory results.",
    lastContactDate: "2026-07-05",
    emailsSentCount: 1
  },
  {
    id: "buyer-4",
    name: "Sodexo Canada Logistics & Procurement",
    country: "Canada",
    city: "Montreal",
    website: "https://www.sodexo.ca",
    email: "procurement@sodexo.ca",
    procurementEmail: "procurement@sodexo.ca",
    realEmail: "info.canada@sodexo.com",
    phone: "+1 514 344 0022",
    realPhone: "+1 514 344 0022",
    headquartersAddress: "3300 Bloor St W, Suite 3600, Toronto, ON M8X 2X2, Canada",
    contactVerified: true,
    linkedIn: "https://linkedin.com/company/sodexo",
    purchasingManager: "Jean-Pierre Tremblay",
    procurementRole: "National Director of Sourcing - Agricultural Produce & Frozen Goods",
    importerType: "Catering Supplier",
    companySize: "Large",
    employees: 3200,
    yearsInBusiness: 28,
    importsFromEgypt: false,
    importsFromTurkey: false,
    importsFromChina: true,
    importsFromIndia: false,
    competitiveOpportunity: "Medium. Looking to diversify from Chinese IQF Mixed Vegetables due to tariff fluctuations. Testing Egyptian mix.",
    recentTriggers: ["Supply Chain Diversification from Asia", "Long-term Institutional Contracts"],
    requiredCrops: ["IQF Mixed Vegetables (Peas, Carrots, Sweetcorn)", "IQF Broccoli Florets"],
    certificationsRequired: ["CFIA Safe Food for Canadians (SFCR)", "HACCP", "BRCGS AA"],
    annualImportVolume: "45 - 75 FCL Containers / Year",
    sourcingChannel: "Foodservice Wholesaler",
    incoterms: "CIF Port of Montreal",
    paymentTerms: "100% LC at Sight via Canadian Chartered Bank",
    destinationPort: "Port of Montreal",
    mrlCompliance: "Health Canada & CFIA Zero Prohibited Chemical Residue Compliance",
    aiScore: 89,
    intentSignalScore: 91,
    status: "Contacted",
    notes: "Sent introductory cold pitch. Received automatic read receipt. Will follow up via phone.",
    lastContactDate: "2026-07-12",
    emailsSentCount: 1
  },
  {
    id: "buyer-5",
    name: "Groupe Pomona Importations S.A.",
    country: "France",
    city: "Paris",
    website: "https://www.groupe-pomona.fr",
    email: "achats@groupe-pomona.fr",
    procurementEmail: "achats@groupe-pomona.fr",
    realEmail: "contact@groupe-pomona.fr",
    phone: "+33 1 5560 4000",
    realPhone: "+33 1 5560 4000",
    headquartersAddress: "3 Avenue du Docteur Ténine, 92160 Antony, France",
    contactVerified: true,
    linkedIn: "https://linkedin.com/company/groupe-pomona",
    purchasingManager: "Amélie Dubois",
    procurementRole: "Directrice des Achats - Surgelés et Fruits & Légumes Bruts",
    importerType: "Wholesaler",
    companySize: "Large",
    employees: 2200,
    yearsInBusiness: 55,
    importsFromEgypt: true,
    importsFromTurkey: true,
    importsFromChina: false,
    importsFromIndia: false,
    competitiveOpportunity: "High. Seeking high-Brix IQF Strawberry and Broccoli. Needs strict BRC/IFS compliance.",
    recentTriggers: ["Seeking Direct Egyptian Supplier for IQF Crops", "Expanding Gourmet Frozen Line"],
    requiredCrops: ["IQF Strawberry Calibrated (15-25mm)", "IQF Cauliflower Florets", "IQF Artichoke"],
    certificationsRequired: ["IFS Food v8 (Higher Level)", "GLOBALG.A.P.", "EU Organic"],
    annualImportVolume: "70 - 110 FCL Containers / Year",
    sourcingChannel: "IQF Frozen Foods",
    incoterms: "CFR Le Havre / Marseille-Fos",
    paymentTerms: "60 Days Net or CAD upon arrival",
    destinationPort: "Port of Le Havre",
    mrlCompliance: "Strict EU MRL (≤ 0.01 mg/kg) + Certificate of Clean Screen",
    aiScore: 94,
    intentSignalScore: 96,
    status: "New Lead",
    notes: "Added to potential target pool. Researching specific category buyer names.",
    lastContactDate: "2026-07-15",
    emailsSentCount: 0
  }
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: "sup-1",
    name: "Al-Delta Agriculture Farms",
    type: "Farm",
    location: "Beheira Governorate, Egypt",
    rating: 4.8,
    certificates: ["GLOBALG.A.P.", "GRASP", "Sedex"],
    productsSourced: ["Strawberry", "Broccoli", "Green Beans"],
    contactPerson: "Haj Mahmoud El-Ghandour",
    phone: "+20 100 234 5678"
  },
  {
    id: "sup-2",
    name: "Suez Logistics Cold Chain",
    type: "Logistics",
    location: "Alexandria, Egypt",
    rating: 4.9,
    certificates: ["ISO 9001", "HACCP", "GDP (Good Distribution Practice)"],
    productsSourced: ["Reefer Shipping", "Customs Clearance", "Cold Storage"],
    contactPerson: "Eng. Sherif Raslan",
    phone: "+20 122 789 1234"
  },
  {
    id: "sup-3",
    name: "Modern Pack Industries Co.",
    type: "Packaging",
    location: "6th of October City, Egypt",
    rating: 4.7,
    certificates: ["BRCGS Packaging", "ISO 22000", "FSC"],
    productsSourced: ["Octabins", "Retail Printed Pouches", "Corrugated Cartons"],
    contactPerson: "Amr Abdel Hadi",
    phone: "+20 111 456 7890"
  },
  {
    id: "sup-4",
    name: "El-Wadi Organic Farms",
    type: "Farm",
    location: "Ismailia Desert Road, Egypt",
    rating: 4.6,
    certificates: ["EU Organic", "USDA Organic", "GLOBALG.A.P."],
    productsSourced: ["Mango", "Okra", "Strawberry"],
    contactPerson: "Dr. Khaled Al-Khatib",
    phone: "+20 102 345 6789"
  }
];

export const INITIAL_EXHIBITIONS: Exhibition[] = [
  {
    id: "ex-1",
    name: "Fruit Logistica",
    date: "February 3-5, 2027",
    location: "Berlin, Germany",
    attendees: "78,000+ Visitors, 3,200+ Exhibitors",
    website: "https://www.fruitlogistica.com",
    description: "The world's leading fresh produce trade show. Invaluable for connecting with Western European, Eastern European, and American frozen food distributors."
  },
  {
    id: "ex-2",
    name: "Gulfood",
    date: "February 15-19, 2027",
    location: "DWTC, Dubai, UAE",
    attendees: "120,000+ Visitors, 5,000+ Exhibitors",
    website: "https://www.gulfood.com",
    description: "The world's largest annual food and beverage trade exhibition. Vital for Middle East, Africa, and Central Asian procurement teams. Galina always secures a massive booth here."
  },
  {
    id: "ex-3",
    name: "Anuga",
    date: "October 9-13, 2027",
    location: "Cologne, Germany",
    attendees: "170,000+ Visitors, 7,500+ Exhibitors",
    website: "https://www.anuga.com",
    description: "The leading global trade fair for the food and beverage industry. Has a massive dedicated pavilion for frozen foods ('Anuga Frozen Food')."
  },
  {
    id: "ex-4",
    name: "SIAL Paris",
    date: "October 17-21, 2026",
    location: "Paris Nord Villepinte, France",
    attendees: "265,000+ Visitors, 7,200+ Exhibitors",
    website: "https://www.sialparis.com",
    description: "A major biennial exhibition that inspires the global food industry. Perfect for negotiating contracts with European supermarkets and catering syndicates."
  },
  {
    id: "ex-5",
    name: "Foodex Japan",
    date: "March 9-12, 2027",
    location: "Tokyo Big Sight, Japan",
    attendees: "85,000+ Visitors, 3,000+ Exhibitors",
    website: "https://www.jma.or.jp/foodex",
    description: "Asia's largest exhibition dedicated to food and drink. Indispensable for breaking into the high-tariff, high-quality Japanese and South Korean IQF markets."
  }
];

export const INITIAL_COMPETITORS: Competitor[] = [
  {
    id: "comp-1",
    name: "Giva Fruit IQF",
    country: "Poland",
    products: ["IQF Strawberry", "IQF Raspberry", "IQF Broccoli"],
    pricingIndex: "Premium",
    certifications: ["BRCGS", "IFS Food", "EU Organic"],
    exhibitions: ["Fruit Logistica", "Anuga", "SIAL"]
  },
  {
    id: "comp-2",
    name: "Ozdem Frozen Foods",
    country: "Turkey",
    products: ["IQF Strawberry", "IQF Green Beans", "IQF Apricot"],
    pricingIndex: "Competitive",
    certifications: ["IFS Food", "BRCGS", "Halal"],
    exhibitions: ["Gulfood", "Fruit Logistica"]
  },
  {
    id: "comp-3",
    name: "Yantai Cold-Chain Produce",
    country: "China",
    products: ["IQF Mixed Vegetables", "IQF Green Peas", "IQF Garlic"],
    pricingIndex: "Economy",
    certifications: ["ISO 22000", "HACCP", "Kosher"],
    exhibitions: ["Foodex Japan", "SIAL"]
  },
  {
    id: "comp-4",
    name: "El-Marwa Food Industries",
    country: "Egypt (Local)",
    products: ["IQF Molokhia", "IQF Okra", "IQF Strawberry", "IQF Mango"],
    pricingIndex: "Competitive",
    certifications: ["HACCP", "ISO 22000", "Halal", "BRCGS"],
    exhibitions: ["Gulfood", "Anuga", "SIAL"]
  }
];
